name: MLOps Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbx_mlops_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks --version

      - name: Set up Databricks profile
        run: |
           export DATABRICKS_HOST=${{ vars.DATABRICKS_HOST }}
           export DATABRICKS_CLIENT_ID=${{ vars.DATABRICKS_CLIENT_ID }}
           export DATABRICKS_CLIENT_SECRET=${{ secrets.DATABRICKS_CLIENT_SECRET }}
      
      - name: Deploy MLOps Bundle
        run: |
           databricks bundle validate --target dev
           databricks bundle deploy --target dev
           databricks bundle run --target dev
